import { mkdir, readFile, writeFile, appendFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { fetchJson, fetchBuffer, USER_AGENT } from "./lib/http.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const force = process.argv.includes("--force");
const rankArg = process.argv.find((a) => a.startsWith("--rank="));
const onlyRanks = rankArg ? new Set(rankArg.split("=")[1].split(",")) : null;
const today = new Date().toISOString().slice(0, 10);

const REJECT = /(nc|nd|non-?free|fair use|unknown|unspecified)/i;
const OK = /(cc0|cc-?by(?!-nc|-nd)|cc by(?!-| nc| nd)|cc-by-sa|cc by-sa|pd|public domain|pdm|cc-pd)/i;

function slug(name) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

function walk(node, fn, parent = null) {
  fn(node, parent);
  for (const child of node.children || []) walk(child, fn, node);
}

function firstSpecies(node) {
  if (node.species?.[0]?.name) return node.species[0].name;
  for (const child of node.children || []) {
    const hit = firstSpecies(child);
    if (hit) return hit;
  }
  return null;
}

function collectTaxa(tree) {
  const nodes = [];
  walk(tree, (node, parent) => {
    if (node.rank === "order" || node.rank === "family" || node.rank === "genus") {
      nodes.push({
        name: node.name,
        rank: node.rank,
        parent: parent?.name,
        typeSpecies: firstSpecies(node),
        family: node.rank === "genus" ? parent?.name : node.rank === "family" ? node.name : null,
        order: node.rank === "order" ? node.name : null
      });
    }
  });
  return nodes;
}

function licenseOk(license) {
  if (!license) return false;
  if (REJECT.test(license) && !/^cc0|public domain|pd/i.test(license)) return false;
  if (/nc|nd/i.test(license) && !/public domain|cc0|pd-old/i.test(license)) return false;
  return OK.test(license) || /pd-old|pdm|cc0/i.test(license);
}

async function writeCreditsMd(credits) {
  const groups = new Map();
  for (const [taxon, entry] of Object.entries(credits)) {
    const list = groups.get(entry.source) || [];
    list.push({ taxon, ...entry });
    groups.set(entry.source, list);
  }
  let md = "# Image credits\n\nAll images were gathered from free-licence sources. None was generated by an image model.\n\n";
  for (const [source, list] of [...groups.entries()].sort()) {
    md += `## ${source}\n\n`;
    for (const item of list.sort((a, b) => a.taxon.localeCompare(b.taxon))) {
      md += `- ${item.taxon} — ${item.title || item.taxon}, ${item.creator} (${item.license}) · ${item.sourceUrl}\n`;
    }
    md += "\n";
  }
  await writeFile(join(root, "CREDITS.md"), md);
}

async function saveImage(rank, name, url, extHint) {
  const destDir = join(root, "assets", "img", rank);
  await mkdir(destDir, { recursive: true });
  const rawDir = join(root, "data", "raw", "img");
  await mkdir(rawDir, { recursive: true });
  const buf = await fetchBuffer(url);
  const ext = extHint || (url.includes(".svg") ? "svg" : "webp");
  const base = slug(name);
  const fileRel = ext === "svg"
    ? `assets/img/${rank}/${base}.svg`
    : `assets/img/${rank}/${base}.webp`;
  const file2xRel = ext === "svg" ? fileRel : `assets/img/${rank}/${base}@2x.webp`;
  await writeFile(join(root, fileRel), buf);
  if (ext !== "svg") await writeFile(join(root, file2xRel), buf);
  await writeFile(join(rawDir, `${rank}-${base}${ext === "svg" ? ".svg" : ".bin"}`), buf);
  return { file: fileRel, file2x: file2xRel };
}

const PHYLOPIC = { Accept: "application/vnd.phylopic.v2+json" };

function pickRaster(files = []) {
  const scored = files
    .map((f) => {
      const [w] = String(f.sizes || "").split("x").map(Number);
      return { href: f.href, w: w || 0 };
    })
    .filter((f) => f.href)
    .sort((a, b) => Math.abs(a.w - 640) - Math.abs(b.w - 640));
  return scored[0]?.href;
}

async function phylopicResolve(name) {
  try {
    const index = await fetchJson(
      `https://api.phylopic.org/nodes?filter_name=${encodeURIComponent(name.toLowerCase())}`,
      PHYLOPIC
    );
    const first = index._links?.firstPage?.href;
    if (!first) return null;
    const page = await fetchJson(`https://api.phylopic.org${first}&embed_items=true`, PHYLOPIC);
    const node = page._embedded?.items?.[0];
    if (!node) return null;
    const imagesHref = node._links?.images?.href || node._links?.cladeImages?.href;
    if (!imagesHref) return null;
    const imgIndex = await fetchJson(`https://api.phylopic.org${imagesHref}`, PHYLOPIC);
    const imgPageHref = imgIndex._links?.firstPage?.href;
    if (!imgPageHref) return null;
    const imgPage = await fetchJson(`https://api.phylopic.org${imgPageHref}&embed_items=true`, PHYLOPIC);
    const image = (imgPage._embedded?.items || [])[0];
    if (!image) return null;
    const vector = image._links?.sourceFile?.href || image._links?.vectorFile?.href;
    const raster = pickRaster(image._links?.rasterFiles);
    const href = vector || raster;
    if (!href) return null;
    const licenseUrl = image._links?.license?.href || "https://creativecommons.org/publicdomain/zero/1.0/";
    const license = /zero/i.test(licenseUrl)
      ? "CC0"
      : /publicdomain|pdm/i.test(licenseUrl)
        ? "PDM"
        : image._links?.license?.title || "CC0";
    if (!licenseOk(`${license} ${licenseUrl}`)) return null;
    const uuid = image._links?.self?.href?.match(/images\/([0-9a-f-]+)/i)?.[1];
    const specific = image._links?.specificNode?.title || image._links?.self?.title || name;
    return {
      kind: "illustration",
      url: href.startsWith("http") ? href : `https://images.phylopic.org${href}`,
      ext: vector ? "svg" : "png",
      title: `${specific} silhouette`,
      creator: image._links?.contributor?.title || "PhyloPic contributor",
      license,
      licenseUrl,
      source: "PhyloPic",
      sourceUrl: uuid ? `https://www.phylopic.org/images/${uuid}` : "https://www.phylopic.org/",
      retrievedAt: today,
      resolvedFromHint: specific
    };
  } catch {
    return null;
  }
}

function commonsLicense(meta) {
  const short = meta?.LicenseShortName?.value || meta?.License?.value || "";
  const url = meta?.LicenseUrl?.value || "";
  return { short, url };
}

const PORTRAIT = /portrait|self-?portrait|bust\b|politician|statesman|people of|memorial to|ole rasmussen|apeness|\blitografi\b|photograph of (a )?(man|woman|person)/i;
const NOT_IMAGE = /\.(pdf|wav|mp3|ogg|oga|flac|mid|midi)(\b|$)|lingualibre|ll-q\d+|bird diversity 2013/i;
const NOT_SUBJECT = /anatomy|skeleton|skull|range map|distribution map|phylogen|cladogram|logo|flag|coat of arms|montage|diversity\.jpg/i;
const PAINTING = /painting|water[ -]?colou?r|gouache|chromolithograph|hand[ -]?colou?red|oil on canvas|audubon|gould|martinet|naumann|brehm|lewin|catesby|edwards|selby|keulemans|fuertes|thorburn|histoire des oiseaux|birds of america/i;

function stripHtml(s) {
  return String(s || "").replace(/<[^>]+>/g, " ");
}

function mentionsTaxon(text, name) {
  const t = text.toLowerCase();
  const n = name.toLowerCase();
  if (t.includes(n)) return true;
  const parts = n.split(/\s+/).filter(Boolean);
  return parts.length > 1 && parts.every((p) => t.includes(p));
}

function hitFromFile(pageTitle, info, used, { source, sourceUrl } = {}) {
  if (!info) return null;
  const title = String(pageTitle || "").replace(/^File:/i, "");
  const desc = stripHtml(info.extmetadata?.ImageDescription?.value);
  const mime = info.mime || "";
  const blob = `${title} ${desc}`;
  if (PORTRAIT.test(blob) || NOT_IMAGE.test(blob) || NOT_SUBJECT.test(blob)) return null;
  if (mime && !mime.startsWith("image/")) return null;
  if (/tiff|tif/i.test(mime) || /\.tiff?$/i.test(title)) return null;
  const fileUrl = info.descriptionshorturl || info.descriptionurl;
  if (used.has(title) || used.has(fileUrl) || used.has(info.url) || used.has(info.thumburl)) return null;
  const { short, url: licUrl } = commonsLicense(info.extmetadata || {});
  if (!licenseOk(`${short} ${licUrl}`)) return null;
  const artist = stripHtml(info.extmetadata?.Artist?.value).trim() || "Unknown";
  const painted = PAINTING.test(blob) || /illustration|plate|drawing|lithograph/i.test(blob);
  return {
    kind: painted ? "illustration" : "photo",
    url: info.thumburl || info.url,
    ext: mime.includes("svg") ? "svg" : "jpg",
    title,
    creator: artist || "Unknown",
    license: short || "Public domain",
    licenseUrl: licUrl || "https://creativecommons.org/publicdomain/mark/1.0/",
    source: source || "Wikimedia Commons",
    sourceUrl: sourceUrl || fileUrl,
    retrievedAt: today
  };
}

async function mediawikiFile(host, fileName) {
  const title = String(fileName || "").replace(/^File:/i, "");
  if (!title) return null;
  const url = `https://${host}/w/api.php?action=query&format=json&redirects=1&titles=${encodeURIComponent(`File:${title}`)}&prop=imageinfo&iiprop=url|extmetadata|mime|size&iiurlwidth=640`;
  const json = await fetchJson(url);
  const page = Object.values(json.query?.pages || {})[0];
  if (!page || page.missing || !page.imageinfo?.[0]) return null;
  return { title: page.title, info: page.imageinfo[0] };
}

async function wikipediaResolve(name, used, { rank } = {}) {
  const titles = [name];
  if (rank === "family") titles.push(`${name} (bird)`, `${name} (family)`);
  else if (rank === "order") titles.push(`${name} (bird)`, `${name} (order)`);
  else titles.push(`${name} (bird)`);

  for (const title of titles) {
    const api = `https://en.wikipedia.org/w/api.php?action=query&format=json&redirects=1&titles=${encodeURIComponent(title)}&prop=pageimages|pageprops|extracts&pithumbsize=640&piprop=name|original|thumbnail&exintro=1&explaintext=1`;
    try {
      const json = await fetchJson(api);
      const page = Object.values(json.query?.pages || {})[0];
      if (!page || page.missing || page.invalid) continue;
      if (page.pageprops && Object.prototype.hasOwnProperty.call(page.pageprops, "disambiguation")) continue;
      if (!page.pageimage) continue;
      const extract = page.extract || "";
      if (/\b(plant|mammal|insect|fish|fungus)\b/i.test(extract) && !/\b(bird|avian|aves)\b/i.test(extract)) continue;
      const wikiUrl = `https://en.wikipedia.org/wiki/${String(page.title).replace(/ /g, "_")}`;
      for (const host of ["commons.wikimedia.org", "en.wikipedia.org"]) {
        try {
          const file = await mediawikiFile(host, page.pageimage);
          if (!file) continue;
          const hit = hitFromFile(file.title, file.info, used, {
            source: "Wikipedia",
            sourceUrl: wikiUrl
          });
          if (hit) return hit;
        } catch {
          continue;
        }
      }
    } catch {
      continue;
    }
  }
  return null;
}

async function wikimediaSearch(name, used) {
  const queries = [
    `"${name}" bird`,
    `intitle:${name} bird`,
    `"${name}" (bird OR avian) (illustration OR plate OR drawing)`
  ];
  const candidates = [];
  for (const query of queries) {
    const url = `https://commons.wikimedia.org/w/api.php?action=query&format=json&origin=*&generator=search&gsrsearch=${encodeURIComponent(query)}&gsrnamespace=6&gsrlimit=12&prop=imageinfo&iiprop=url|extmetadata|mime|size&iiurlwidth=640`;
    try {
      const json = await fetchJson(url);
      const pages = Object.values(json.query?.pages || {});
      for (const page of pages) {
        const info = page.imageinfo?.[0];
        if (!info) continue;
        if (!mentionsTaxon(`${page.title} ${stripHtml(info.extmetadata?.ImageDescription?.value)}`, name)) continue;
        const hit = hitFromFile(page.title, info, used, { source: "Wikimedia Commons" });
        if (hit) candidates.push(hit);
      }
      if (candidates[0]) return candidates[0];
    } catch {
      continue;
    }
  }
  return candidates[0] || null;
}

async function openverseSearch(name, used) {
  try {
    const url = `https://api.openverse.org/v1/images/?q=${encodeURIComponent(`"${name}" bird`)}&license_type=commercial,modification&page_size=8`;
    const json = await fetchJson(url);
    for (const r of json.results || []) {
      const blob = `${r.title || ""} ${r.id || ""}`;
      if (PORTRAIT.test(blob) || !mentionsTaxon(blob, name)) continue;
      if (used.has(r.foreign_landing_url) || used.has(r.url)) continue;
      if (!licenseOk(r.license || "")) continue;
      const painted = PAINTING.test(blob) || /illustration|plate|drawing/i.test(blob);
      return {
        kind: painted ? "illustration" : "photo",
        url: r.url,
        ext: "jpg",
        title: r.title || name,
        creator: r.creator || "Unknown",
        license: (r.license || "cc0").toUpperCase(),
        licenseUrl: r.license_url || "https://creativecommons.org/publicdomain/zero/1.0/",
        source: "Openverse",
        sourceUrl: r.foreign_landing_url || r.url,
        retrievedAt: today
      };
    }
  } catch {
    return null;
  }
  return null;
}

async function inatPhoto(name) {
  try {
    const url = `https://api.inaturalist.org/v1/taxa?q=${encodeURIComponent(name)}&rank=genus,family,order&per_page=5`;
    const json = await fetchJson(url);
    for (const t of json.results || []) {
      const matched = `${t.name || ""} ${t.preferred_common_name || ""} ${t.matched_term || ""}`;
      if (!mentionsTaxon(matched, name)) continue;
      const photo = t.default_photo;
      if (!photo) continue;
      const lic = photo.license_code || "";
      if (!licenseOk(lic)) continue;
      return {
        kind: "photo",
        url: photo.medium_url || photo.url,
        ext: "jpg",
        title: photo.attribution || name,
        creator: photo.attribution || "Unknown",
        license: lic.toUpperCase(),
        licenseUrl: "https://creativecommons.org/licenses/",
        source: "iNaturalist",
        sourceUrl: `https://www.inaturalist.org/taxa/${t.id}`,
        retrievedAt: today
      };
    }
  } catch {
    return null;
  }
  return null;
}

function isBadCredit(entry) {
  if (!entry) return true;
  const blob = `${entry.title} ${entry.file} ${entry.sourceUrl}`;
  return PORTRAIT.test(entry.title || "")
    || NOT_IMAGE.test(blob)
    || NOT_SUBJECT.test(blob)
    || /apeness|ole rasmussen|kutorgina|crotalaria/i.test(blob);
}

function isUpgradeable(entry, credits = {}) {
  if (!entry?.file || isBadCredit(entry)) return true;
  if (entry.source !== "Wikipedia") return true;
  if (!entry.title) return false;
  let n = 0;
  for (const other of Object.values(credits)) {
    if (other.title === entry.title) n += 1;
  }
  return n > 1;
}

async function resolveOne(taxon, climbTo, used) {
  const names = [taxon.name];
  if (taxon.typeSpecies) names.push(taxon.typeSpecies);
  if (climbTo) names.push(climbTo);
  for (const name of names) {
    const wiki = await wikipediaResolve(name, used, { rank: name === taxon.name ? taxon.rank : undefined });
    if (wiki) return { ...wiki, resolvedFrom: name };
  }
  for (const name of names) {
    const commons = await wikimediaSearch(name, used);
    if (commons) return { ...commons, resolvedFrom: name };
    const open = await openverseSearch(name, used);
    if (open) return { ...open, resolvedFrom: name };
  }
  for (const name of names) {
    const hit = (await phylopicResolve(name)) || (await inatPhoto(name));
    if (hit) return { ...hit, resolvedFrom: hit.resolvedFromHint || name };
  }
  return null;
}

async function main() {
  const tree = JSON.parse(await readFile(join(root, "data", "birds.json"), "utf8"));
  const creditsPath = join(root, "assets", "credits.json");
  let credits = {};
  try { credits = JSON.parse(await readFile(creditsPath, "utf8")); } catch { credits = {}; }

  const taxa = collectTaxa(tree).filter((t) => !onlyRanks || onlyRanks.has(t.rank));
  const missingPath = join(root, "data", "raw", "missing-images.txt");
  await mkdir(join(root, "data", "raw"), { recursive: true });
  await writeFile(missingPath, "");

  let resolved = 0;
  let inherited = 0;
  let photos = 0;
  let missing = 0;
  const used = new Set(
    Object.values(credits)
      .filter((c) => !isBadCredit(c) && !isUpgradeable(c, credits))
      .flatMap((c) => [c.sourceUrl, c.file, c.title])
  );

  for (const taxon of taxa) {
    const existing = credits[taxon.name];
    if (!force && existing?.file && !isUpgradeable(existing, credits)) {
      resolved += 1;
      if (existing.resolvedFrom && existing.resolvedFrom !== taxon.name) inherited += 1;
      if (existing.kind === "photo") photos += 1;
      used.add(existing.sourceUrl);
      continue;
    }
    const climb = taxon.rank === "genus" ? taxon.family : taxon.rank === "family" ? taxon.parent : null;
    process.stdout.write(`image ${taxon.rank} ${taxon.name} … `);
    const hit = await resolveOne(taxon, climb, used);
    if (!hit) {
      if (existing?.file && !isBadCredit(existing)) {
        resolved += 1;
        console.log("kept existing");
        continue;
      }
      console.log("missing");
      missing += 1;
      await appendFile(missingPath, `${taxon.rank}\t${taxon.name}\n`);
      continue;
    }
    let saved;
    try {
      saved = await saveImage(taxon.rank, taxon.name, hit.url, hit.ext);
    } catch (err) {
      console.log(`download failed (${err.cause?.code || err.message})`);
      missing += 1;
      await appendFile(missingPath, `${taxon.rank}\t${taxon.name}\n`);
      continue;
    }
    credits[taxon.name] = {
      rank: taxon.rank,
      kind: hit.kind,
      file: saved.file,
      file2x: saved.file2x,
      title: hit.title,
      creator: hit.creator,
      license: hit.license,
      licenseUrl: hit.licenseUrl,
      source: hit.source,
      sourceUrl: hit.sourceUrl,
      resolvedFrom: hit.resolvedFrom,
      retrievedAt: today
    };
    if (hit.resolvedFrom !== taxon.name) inherited += 1;
    if (hit.kind === "photo") photos += 1;
    resolved += 1;
    used.add(hit.sourceUrl);
    used.add(hit.url);
    used.add(hit.title);
    await writeFile(creditsPath, JSON.stringify(credits, null, 2));
    console.log(`${hit.source} (${hit.kind}) · ${hit.title}`);
  }

  for (const [name, entry] of Object.entries(credits)) {
    if (!entry.license || !entry.sourceUrl) {
      throw new Error(`Credit for ${name} missing license or sourceUrl`);
    }
  }

  await writeCreditsMd(credits);

  const byRank = { order: { total: 0, ok: 0 }, family: { total: 0, ok: 0 }, genus: { total: 0, ok: 0 } };
  for (const t of taxa) {
    byRank[t.rank].total += 1;
    if (credits[t.name]) byRank[t.rank].ok += 1;
  }
  const illustration = Object.values(credits).filter((c) => c.kind !== "photo").length;
  const totalCred = Object.keys(credits).length;

  console.log("\ncoverage");
  console.table({
    nodes: taxa.length,
    resolved,
    inherited,
    photos,
    missing,
    illustrationPct: totalCred ? ((illustration / totalCred) * 100).toFixed(1) : "0",
    orders: `${byRank.order.ok}/${byRank.order.total}`,
    families: `${byRank.family.ok}/${byRank.family.total}`,
    genera: `${byRank.genus.ok}/${byRank.genus.total}`
  });

  const orderPct = byRank.order.total ? byRank.order.ok / byRank.order.total : 1;
  const familyPct = byRank.family.total ? byRank.family.ok / byRank.family.total : 1;
  const genusPct = byRank.genus.total ? byRank.genus.ok / byRank.genus.total : 1;
  if (orderPct < 1 || familyPct < 0.95 || genusPct < 0.8) {
    console.error("Coverage targets missed (not loosening licence filters):");
    if (byRank.order.total && orderPct < 1) console.error(` orders ${(orderPct * 100).toFixed(1)}% < 100%`);
    if (byRank.family.total && familyPct < 0.95) console.error(` families ${(familyPct * 100).toFixed(1)}% < 95%`);
    if (byRank.genus.total && genusPct < 0.8) console.error(` genera ${(genusPct * 100).toFixed(1)}% < 80%`);
    process.exitCode = 1;
  }

  void USER_AGENT;
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
