import { mkdir, readFile, writeFile, appendFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { fetchJson, fetchBuffer, USER_AGENT } from "./lib/http.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const force = process.argv.includes("--force");
const rankArg = process.argv.find((a) => a.startsWith("--rank="));
const onlyRanks = rankArg ? new Set(rankArg.split("=")[1].split(",")) : null;
const today = new Date().toISOString().slice(0, 10);

const REJECT = /(nc|nd|non-?free|fair use|unknown|unspecified)/i;
const OK = /(cc0|cc-?by(?!-nc|-nd)|cc by(?!-| nc| nd)|cc-by-sa|cc by-sa|pd|public domain|pdm|cc-pd)/i;

function slug(name) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

function walk(node, fn, parent = null) {
  fn(node, parent);
  for (const child of node.children || []) walk(child, fn, node);
}

function collectTaxa(tree) {
  const nodes = [];
  walk(tree, (node, parent) => {
    if (node.rank === "order" || node.rank === "family" || node.rank === "genus") {
      nodes.push({
        name: node.name,
        rank: node.rank,
        parent: parent?.name,
        typeSpecies: node.species?.[0]?.name || null,
        family: node.rank === "genus" ? parent?.name : node.rank === "family" ? node.name : null,
        order: node.rank === "order" ? node.name : null
      });
    }
  });
  return nodes;
}

function licenseOk(license) {
  if (!license) return false;
  if (REJECT.test(license) && !/^cc0|public domain|pd/i.test(license)) return false;
  if (/nc|nd/i.test(license) && !/public domain|cc0|pd-old/i.test(license)) return false;
  return OK.test(license) || /pd-old|pdm|cc0/i.test(license);
}

async function writeCreditsMd(credits) {
  const groups = new Map();
  for (const [taxon, entry] of Object.entries(credits)) {
    const list = groups.get(entry.source) || [];
    list.push({ taxon, ...entry });
    groups.set(entry.source, list);
  }
  let md = "# Image credits\n\nAll artwork was gathered from free-licence sources. None was generated by an image model.\n\n";
  for (const [source, list] of [...groups.entries()].sort()) {
    md += `## ${source}\n\n`;
    for (const item of list.sort((a, b) => a.taxon.localeCompare(b.taxon))) {
      md += `- ${item.taxon} — ${item.title || item.taxon}, ${item.creator} (${item.license}) · ${item.sourceUrl}\n`;
    }
    md += "\n";
  }
  await writeFile(join(root, "CREDITS.md"), md);
}

async function saveImage(rank, name, url, extHint) {
  const destDir = join(root, "assets", "img", rank);
  await mkdir(destDir, { recursive: true });
  const rawDir = join(root, "data", "raw", "img");
  await mkdir(rawDir, { recursive: true });
  const buf = await fetchBuffer(url);
  const ext = extHint || (url.includes(".svg") ? "svg" : "webp");
  const base = slug(name);
  const fileRel = ext === "svg"
    ? `assets/img/${rank}/${base}.svg`
    : `assets/img/${rank}/${base}.webp`;
  const file2xRel = ext === "svg" ? fileRel : `assets/img/${rank}/${base}@2x.webp`;
  await writeFile(join(root, fileRel), buf);
  if (ext !== "svg") await writeFile(join(root, file2xRel), buf);
  await writeFile(join(rawDir, `${rank}-${base}${ext === "svg" ? ".svg" : ".bin"}`), buf);
  return { file: fileRel, file2x: file2xRel };
}

const PHYLOPIC = { Accept: "application/vnd.phylopic.v2+json" };

function pickRaster(files = []) {
  const scored = files
    .map((f) => {
      const [w] = String(f.sizes || "").split("x").map(Number);
      return { href: f.href, w: w || 0 };
    })
    .filter((f) => f.href)
    .sort((a, b) => Math.abs(a.w - 640) - Math.abs(b.w - 640));
  return scored[0]?.href;
}

async function phylopicResolve(name) {
  try {
    const index = await fetchJson(
      `https://api.phylopic.org/nodes?filter_name=${encodeURIComponent(name.toLowerCase())}`,
      PHYLOPIC
    );
    const first = index._links?.firstPage?.href;
    if (!first) return null;
    const page = await fetchJson(`https://api.phylopic.org${first}&embed_items=true`, PHYLOPIC);
    const node = page._embedded?.items?.[0];
    if (!node) return null;
    const imagesHref = node._links?.images?.href || node._links?.cladeImages?.href;
    if (!imagesHref) return null;
    const imgIndex = await fetchJson(`https://api.phylopic.org${imagesHref}`, PHYLOPIC);
    const imgPageHref = imgIndex._links?.firstPage?.href;
    if (!imgPageHref) return null;
    const imgPage = await fetchJson(`https://api.phylopic.org${imgPageHref}&embed_items=true`, PHYLOPIC);
    const image = (imgPage._embedded?.items || [])[0];
    if (!image) return null;
    const vector = image._links?.sourceFile?.href || image._links?.vectorFile?.href;
    const raster = pickRaster(image._links?.rasterFiles);
    const href = vector || raster;
    if (!href) return null;
    const licenseUrl = image._links?.license?.href || "https://creativecommons.org/publicdomain/zero/1.0/";
    const license = /zero/i.test(licenseUrl)
      ? "CC0"
      : /publicdomain|pdm/i.test(licenseUrl)
        ? "PDM"
        : image._links?.license?.title || "CC0";
    if (!licenseOk(`${license} ${licenseUrl}`)) return null;
    const uuid = image._links?.self?.href?.match(/images\/([0-9a-f-]+)/i)?.[1];
    const specific = image._links?.specificNode?.title || image._links?.self?.title || name;
    return {
      kind: "illustration",
      url: href.startsWith("http") ? href : `https://images.phylopic.org${href}`,
      ext: vector ? "svg" : "png",
      title: `${specific} silhouette`,
      creator: image._links?.contributor?.title || "PhyloPic contributor",
      license,
      licenseUrl,
      source: "PhyloPic",
      sourceUrl: uuid ? `https://www.phylopic.org/images/${uuid}` : "https://www.phylopic.org/",
      retrievedAt: today,
      resolvedFromHint: specific
    };
  } catch {
    return null;
  }
}

function commonsLicense(meta) {
  const short = meta?.LicenseShortName?.value || meta?.License?.value || "";
  const url = meta?.LicenseUrl?.value || "";
  return { short, url };
}

const PORTRAIT = /portrait|self-?portrait|bust\b|politician|statesman|people of|memorial to|ole rasmussen|apeness|\blitografi\b|photograph of (a )?(man|woman|person)/i;

function stripHtml(s) {
  return String(s || "").replace(/<[^>]+>/g, " ");
}

function mentionsTaxon(text, name) {
  const t = text.toLowerCase();
  const n = name.toLowerCase();
  if (t.includes(n)) return true;
  const parts = n.split(/\s+/).filter(Boolean);
  return parts.length > 1 && parts.every((p) => t.includes(p));
}

function isAnimalish(text) {
  return /(illustration|plate|drawing|lithograph|silhouette|mammal|animal|bat|cat|dog|whale|deer|rodent|primate|marsupial|ungulate|brehm|lydekker|haeckel|audubon)/i.test(text);
}

async function wikimediaSearch(name, used) {
  const queries = [
    `intitle:${name} (illustration OR plate OR drawing OR silhouette)`,
    `"${name}" (mammal OR animal) (illustration OR plate OR drawing)`,
    `intitle:${name}`
  ];
  for (const query of queries) {
    const url = `https://commons.wikimedia.org/w/api.php?action=query&format=json&origin=*&generator=search&gsrsearch=${encodeURIComponent(query)}&gsrnamespace=6&gsrlimit=12&prop=imageinfo&iiprop=url|extmetadata|mime|size&iiurlwidth=640`;
    try {
      const json = await fetchJson(url);
      const pages = Object.values(json.query?.pages || {});
      for (const page of pages) {
        const info = page.imageinfo?.[0];
        if (!info) continue;
        const title = page.title.replace(/^File:/, "");
        const desc = stripHtml(info.extmetadata?.ImageDescription?.value);
        const blob = `${title} ${desc}`;
        if (PORTRAIT.test(blob)) continue;
        if (!mentionsTaxon(blob, name) && !isAnimalish(blob)) continue;
        if (!mentionsTaxon(blob, name)) continue;
        const sourceUrl = info.descriptionshorturl || info.descriptionurl;
        if (used.has(sourceUrl) || used.has(info.url)) continue;
        const { short, url: licUrl } = commonsLicense(info.extmetadata || {});
        if (!licenseOk(`${short} ${licUrl}`)) continue;
        const artist = stripHtml(info.extmetadata?.Artist?.value).trim() || "Unknown";
        const mime = info.mime || "";
        return {
          kind: "illustration",
          url: info.thumburl || info.url,
          ext: mime.includes("svg") ? "svg" : "jpg",
          title,
          creator: artist || "Unknown",
          license: short || "Public domain",
          licenseUrl: licUrl || "https://creativecommons.org/publicdomain/mark/1.0/",
          source: "Wikimedia Commons",
          sourceUrl,
          retrievedAt: today
        };
      }
    } catch {
      continue;
    }
  }
  return null;
}

async function openverseSearch(name, used) {
  try {
    const url = `https://api.openverse.org/v1/images/?q=${encodeURIComponent(`"${name}" illustration mammal`)}&license_type=commercial,modification&page_size=8`;
    const json = await fetchJson(url);
    for (const r of json.results || []) {
      const blob = `${r.title || ""} ${r.id || ""}`;
      if (PORTRAIT.test(blob) || !mentionsTaxon(blob, name)) continue;
      if (used.has(r.foreign_landing_url) || used.has(r.url)) continue;
      if (!licenseOk(r.license || "")) continue;
      return {
        kind: "illustration",
        url: r.url,
        ext: "jpg",
        title: r.title || name,
        creator: r.creator || "Unknown",
        license: (r.license || "cc0").toUpperCase(),
        licenseUrl: r.license_url || "https://creativecommons.org/publicdomain/zero/1.0/",
        source: "Openverse",
        sourceUrl: r.foreign_landing_url || r.url,
        retrievedAt: today
      };
    }
  } catch {
    return null;
  }
  return null;
}

async function inatPhoto(name) {
  try {
    const url = `https://api.inaturalist.org/v1/taxa?q=${encodeURIComponent(name)}&rank=genus,family,order&per_page=5`;
    const json = await fetchJson(url);
    for (const t of json.results || []) {
      const matched = `${t.name || ""} ${t.preferred_common_name || ""} ${t.matched_term || ""}`;
      if (!mentionsTaxon(matched, name)) continue;
      const photo = t.default_photo;
      if (!photo) continue;
      const lic = photo.license_code || "";
      if (!licenseOk(lic)) continue;
      return {
        kind: "photo",
        url: photo.medium_url || photo.url,
        ext: "jpg",
        title: photo.attribution || name,
        creator: photo.attribution || "Unknown",
        license: lic.toUpperCase(),
        licenseUrl: "https://creativecommons.org/licenses/",
        source: "iNaturalist",
        sourceUrl: `https://www.inaturalist.org/taxa/${t.id}`,
        retrievedAt: today
      };
    }
  } catch {
    return null;
  }
  return null;
}

function isBadCredit(entry) {
  if (!entry) return true;
  return PORTRAIT.test(entry.title || "") || /apeness|ole rasmussen|kutorgina/i.test(`${entry.title} ${entry.sourceUrl}`);
}

async function resolveOne(taxon, climbTo, used) {
  const names = [taxon.name];
  if (taxon.typeSpecies) names.push(taxon.typeSpecies);
  if (climbTo) names.push(climbTo);
  for (const name of names) {
    const hit =
      (await phylopicResolve(name)) ||
      (await wikimediaSearch(name, used)) ||
      (await openverseSearch(name, used)) ||
      (await inatPhoto(name));
    if (hit) {
      return { ...hit, resolvedFrom: hit.resolvedFromHint || name };
    }
  }
  return null;
}

async function main() {
  const tree = JSON.parse(await readFile(join(root, "data", "mammals.json"), "utf8"));
  const creditsPath = join(root, "assets", "credits.json");
  let credits = {};
  try { credits = JSON.parse(await readFile(creditsPath, "utf8")); } catch { credits = {}; }

  const taxa = collectTaxa(tree).filter((t) => !onlyRanks || onlyRanks.has(t.rank));
  const missingPath = join(root, "data", "raw", "missing-images.txt");
  await mkdir(join(root, "data", "raw"), { recursive: true });
  await writeFile(missingPath, "");

  let resolved = 0;
  let inherited = 0;
  let photos = 0;
  let missing = 0;
  const used = new Set(
    Object.values(credits)
      .filter((c) => !isBadCredit(c))
      .flatMap((c) => [c.sourceUrl, c.file])
  );

  for (const taxon of taxa) {
    if (!force && credits[taxon.name]?.file && !isBadCredit(credits[taxon.name])) {
      resolved += 1;
      if (credits[taxon.name].resolvedFrom && credits[taxon.name].resolvedFrom !== taxon.name) inherited += 1;
      if (credits[taxon.name].kind === "photo") photos += 1;
      used.add(credits[taxon.name].sourceUrl);
      continue;
    }
    const climb = taxon.rank === "genus" ? taxon.family : taxon.rank === "family" ? taxon.parent : null;
    process.stdout.write(`image ${taxon.rank} ${taxon.name} … `);
    const hit = await resolveOne(taxon, climb, used);
    if (!hit) {
      console.log("missing");
      missing += 1;
      await appendFile(missingPath, `${taxon.rank}\t${taxon.name}\n`);
      continue;
    }
    let saved;
    try {
      saved = await saveImage(taxon.rank, taxon.name, hit.url, hit.ext);
    } catch (err) {
      console.log(`download failed (${err.cause?.code || err.message})`);
      missing += 1;
      await appendFile(missingPath, `${taxon.rank}\t${taxon.name}\n`);
      continue;
    }
    credits[taxon.name] = {
      rank: taxon.rank,
      kind: hit.kind,
      file: saved.file,
      file2x: saved.file2x,
      title: hit.title,
      creator: hit.creator,
      license: hit.license,
      licenseUrl: hit.licenseUrl,
      source: hit.source,
      sourceUrl: hit.sourceUrl,
      resolvedFrom: hit.resolvedFrom,
      retrievedAt: today
    };
    if (hit.resolvedFrom !== taxon.name) inherited += 1;
    if (hit.kind === "photo") photos += 1;
    resolved += 1;
    used.add(hit.sourceUrl);
    used.add(hit.url);
    await writeFile(creditsPath, JSON.stringify(credits, null, 2));
    console.log(`${hit.source} (${hit.kind}) · ${hit.title}`);
  }

  for (const [name, entry] of Object.entries(credits)) {
    if (!entry.license || !entry.sourceUrl) {
      throw new Error(`Credit for ${name} missing license or sourceUrl`);
    }
  }

  await writeCreditsMd(credits);

  const byRank = { order: { total: 0, ok: 0 }, family: { total: 0, ok: 0 }, genus: { total: 0, ok: 0 } };
  for (const t of taxa) {
    byRank[t.rank].total += 1;
    if (credits[t.name]) byRank[t.rank].ok += 1;
  }
  const illustration = Object.values(credits).filter((c) => c.kind !== "photo").length;
  const totalCred = Object.keys(credits).length;

  console.log("\ncoverage");
  console.table({
    nodes: taxa.length,
    resolved,
    inherited,
    photos,
    missing,
    illustrationPct: totalCred ? ((illustration / totalCred) * 100).toFixed(1) : "0",
    orders: `${byRank.order.ok}/${byRank.order.total}`,
    families: `${byRank.family.ok}/${byRank.family.total}`,
    genera: `${byRank.genus.ok}/${byRank.genus.total}`
  });

  const orderPct = byRank.order.total ? byRank.order.ok / byRank.order.total : 1;
  const familyPct = byRank.family.total ? byRank.family.ok / byRank.family.total : 1;
  const genusPct = byRank.genus.total ? byRank.genus.ok / byRank.genus.total : 1;
  const illPct = totalCred ? illustration / totalCred : 0;
  if (orderPct < 1 || familyPct < 0.95 || genusPct < 0.8 || illPct < 0.7) {
    console.error("Coverage targets missed (not loosening licence filters):");
    if (byRank.order.total && orderPct < 1) console.error(` orders ${(orderPct * 100).toFixed(1)}% < 100%`);
    if (byRank.family.total && familyPct < 0.95) console.error(` families ${(familyPct * 100).toFixed(1)}% < 95%`);
    if (byRank.genus.total && genusPct < 0.8) console.error(` genera ${(genusPct * 100).toFixed(1)}% < 80%`);
    if (illPct < 0.7) console.error(` illustrations ${(illPct * 100).toFixed(1)}% < 70%`);
    process.exitCode = 1;
  }

  void USER_AGENT;
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
